/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TButton: typeof import('tov-ui')['Button']
    TInput: typeof import('tov-ui')['Input']
    TTable: typeof import('tov-ui')['Table']
    TTableColumn: typeof import('tov-ui')['TableColumn']
    TTooltip: typeof import('tov-ui')['Tooltip']
    TVirtualList: typeof import('tov-ui')['VirtualList']
  }
}
